# Generated by Django 6.0.3 on 2026-03-21 14:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_document_houseinfo_notification_requestreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShutdownSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('hot_water', 'Горячая вода'), ('cold_water', 'Холодная вода'), ('electricity', 'Электричество'), ('heating', 'Отопление'), ('gas', 'Газ')], max_length=20, verbose_name='Тип услуги')),
                ('start_date', models.DateTimeField(verbose_name='Начало отключения')),
                ('end_date', models.DateTimeField(verbose_name='Окончание отключения')),
                ('address', models.CharField(blank=True, help_text='Оставьте пустым для всего дома', max_length=200, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Причина')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'График отключений',
                'verbose_name_plural': 'График отключений',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Количество отзывов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('experience', models.IntegerField(default=0, verbose_name='Стаж (лет)')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='EmployeeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.employee', verbose_name='Сотрудник')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.request', verbose_name='Заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв о сотруднике',
                'verbose_name_plural': 'Отзывы о сотрудниках',
            },
        ),
    ]
